// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	integrations: [
		starlight({
			title: 'Aquazaku Docs',
			description:
				'Documentación técnica del sistema de gestión de Aquazaku: ventas, stock, clientes, proveedores y app mobile.',
			// Español sin prefijo /es/ en la URL.
			defaultLocale: 'root',
			locales: {
				root: { label: 'Español', lang: 'es' },
			},
			social: [
				{
					icon: 'github',
					label: 'GitHub',
					href: 'https://github.com/maoacr/aquazaku-docs',
				},
			],
			// `autogenerate` lee el filesystem: agregar un .md crea la entrada sola.
			// No hace falta tocar este archivo cada vez que documentamos algo nuevo.
			//
			// Desde Starlight 0.39 el autogenerate NO puede ir junto al `label`:
			// tiene que estar dentro de `items`. Ver:
			// https://starlight.astro.build/guides/sidebar/#autogenerated-groups
			sidebar: [
				{
					label: 'Empezar acá',
					items: [
						{ label: 'Visión general', slug: 'empezar/vision-general' },
						{ label: 'Glosario del negocio', slug: 'empezar/glosario' },
					],
				},
				{
					label: 'Arquitectura',
					items: [{ autogenerate: { directory: 'arquitectura' } }],
				},
				{
					label: 'Decisiones técnicas (ADR)',
					collapsed: true,
					items: [{ autogenerate: { directory: 'decisiones' } }],
				},
				{
					label: 'Dominio',
					items: [{ autogenerate: { directory: 'dominio' } }],
				},
				{
					label: 'Backend',
					items: [{ autogenerate: { directory: 'backend' } }],
				},
				{
					label: 'Base de datos',
					items: [{ autogenerate: { directory: 'base-de-datos' } }],
				},
				{
					label: 'Frontend',
					items: [{ autogenerate: { directory: 'frontend' } }],
				},
				{
					label: 'Mobile',
					items: [{ autogenerate: { directory: 'mobile' } }],
				},
				{
					label: 'Convenciones',
					collapsed: true,
					items: [{ autogenerate: { directory: 'convenciones' } }],
				},
			],
		}),
	],
});
